[package]
name = "collections"
version = "0.1.0"
authors = ["Albert Liu <albertymliu@gmail.com>"]
edition = "2018"
description = "'Collections' interfaces for describing objects that contain other objects"
license = "MIT"
license-file = "LICENSE"

[dependencies]
